import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
} from '@clerk/nextjs'
import {ToastContainer} from 'react-toastify'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ReduxWrapper from '../components/custom-components/ReduxWrapper'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Todo-List App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <div className=' md:p-20 sm:p-10 max-sm:p-5'>
            <ReduxWrapper>
              {children}
            </ReduxWrapper>
          </div>
          <ToastContainer/>
        </body>
      </html>
    </ClerkProvider>
  )
}